# DO-NOT-EDIT: Generated by github:vic/flake-file
# To re-generate: nix-shell . -A flake-file.sh --run write-deps
# Usage: let deps = import ./deps.nix; in deps.nixpkgs.outPath
{
  antigravity = {
    outPath = builtins.fetchTarball { url = "https://github.com/jacopone/antigravity-nix/archive/df4ceb04f51e2dfff620752242ce8488ff53c08d.tar.gz"; sha256 = "06jqk3gq47wz62wx96capz9lpb2xrhqa7dzi2488y4vk4ij6bqz9"; };
    type = "github";
    owner = "jacopone";
    repo = "antigravity-nix";
    rev = "df4ceb04f51e2dfff620752242ce8488ff53c08d";
    host = "github.com";
  };
  den = {
    outPath = builtins.fetchTarball { url = "https://github.com/vic/den/archive/311d77a3afee7c0f3cd3d4f494b5129b17c12aa2.tar.gz"; sha256 = "1v1gc5d1dxnfn38xh0g434556nwzyvpadd23cc79m9f3xk0mgz2n"; };
    type = "github";
    owner = "vic";
    repo = "den";
    rev = "311d77a3afee7c0f3cd3d4f494b5129b17c12aa2";
    host = "github.com";
  };
  enthium = {
    outPath = builtins.fetchTarball { url = "https://github.com/sunaku/enthium/archive/832ac5562b00e2b0776e5268b04c19ebe0eabfb7.tar.gz"; sha256 = "1h7anx5jr9adnd9ssj2v6qb685pzv24pi6sb32a01lx464fzwafn"; };
    type = "github";
    owner = "sunaku";
    repo = "enthium";
    rev = "832ac5562b00e2b0776e5268b04c19ebe0eabfb7";
    ref = "v10";
    host = "github.com";
  };
  flake-aspects = {
    outPath = builtins.fetchTarball { url = "https://github.com/vic/flake-aspects/archive/88bac0fd89f3d9ce8f157debc57875ca470535e8.tar.gz"; sha256 = "06j2jd0y74vma74ilvfl0kswywpjnjnjvp1kaw0n49251pvasybs"; };
    type = "github";
    owner = "vic";
    repo = "flake-aspects";
    rev = "88bac0fd89f3d9ce8f157debc57875ca470535e8";
    host = "github.com";
  };
  flake-file = {
    outPath = builtins.fetchTarball { url = "https://github.com/vic/flake-file/archive/c9d91bd7e79c45d8b14967e7cb2db410ab7f3530.tar.gz"; sha256 = "083h8839sz2phpfsp3ri313dfxjz8qkj7kz3ilav072mrip4rn41"; };
    type = "github";
    owner = "vic";
    repo = "flake-file";
    rev = "c9d91bd7e79c45d8b14967e7cb2db410ab7f3530";
    host = "github.com";
  };
  flake-utils = {
    outPath = builtins.fetchTarball { url = "https://github.com/numtide/flake-utils/archive/11707dc2f618dd54ca8739b309ec4fc024de578b.tar.gz"; sha256 = "1cii9id0k1vsa3r53k54bndyl6kxzgm1nsgj7gncgbp3j61qahlp"; };
    type = "github";
    owner = "numtide";
    repo = "flake-utils";
    rev = "11707dc2f618dd54ca8739b309ec4fc024de578b";
    host = "github.com";
  };
  helium = {
    outPath = builtins.fetchTarball { url = "https://github.com/schembriaiden/helium-browser-nix-flake/archive/9001c8ec8bb3a4b9103eca2f2fc707bda1401977.tar.gz"; sha256 = "0xw5yqqyvrdc4bl41ay112cjaj62f8smir4ks5z6cwfzh2yqgxhm"; };
    type = "github";
    owner = "schembriaiden";
    repo = "helium-browser-nix-flake";
    rev = "9001c8ec8bb3a4b9103eca2f2fc707bda1401977";
    host = "github.com";
  };
  import-tree = {
    outPath = builtins.fetchTarball { url = "https://github.com/vic/import-tree/archive/78c35e32f2b499c25e0671e41662537a6b1edbf0.tar.gz"; sha256 = "0srs0shmwwqvghvlbvqg70rjk16n1cvjnpr9smd5mdxicn0xaiq2"; };
    type = "github";
    owner = "vic";
    repo = "import-tree";
    rev = "78c35e32f2b499c25e0671e41662537a6b1edbf0";
    host = "github.com";
  };
  jjdag = {
    outPath = builtins.fetchTarball { url = "https://github.com/anthrofract/jjdag/archive/9d2c745e3fbc1c15a10691e72295a64e07c338ff.tar.gz"; sha256 = "0njwwxj367351pfk5355vj2zdzdcgxh4l45v6n8q6hhq439vfq6s"; };
    type = "github";
    owner = "anthrofract";
    repo = "jjdag";
    rev = "9d2c745e3fbc1c15a10691e72295a64e07c338ff";
    host = "github.com";
  };
  jjui = {
    outPath = builtins.fetchTarball { url = "https://github.com/idursun/jjui/archive/e07315fa5d254dfca9df96a862fe76a329ec4b8e.tar.gz"; sha256 = "1hba7h1yc8ywzcfww84shjxwlvkhr2fbd5y1bf6c7ic31y5iv5xh"; };
    type = "github";
    owner = "idursun";
    repo = "jjui";
    rev = "e07315fa5d254dfca9df96a862fe76a329ec4b8e";
    host = "github.com";
  };
  neomacs = {
    outPath = builtins.fetchTarball { url = "https://github.com/eval-exec/neomacs/archive/9152f7754f878a69b458cb7e0d8d06e3137decfd.tar.gz"; sha256 = "0h0dd3lm1260k83376kiz8gsyhahwfa7sc4kxjph3azmfxs16wh1"; };
    type = "github";
    owner = "eval-exec";
    repo = "neomacs";
    rev = "9152f7754f878a69b458cb7e0d8d06e3137decfd";
    host = "github.com";
  };
  nix-darwin = {
    outPath = builtins.fetchTarball { url = "https://github.com/LnL7/nix-darwin/archive/3bfa436c1975674ca465ce34586467be301ff509.tar.gz"; sha256 = "0r5p5jh06dk2cfklav9fk127izagnap9a6r7a9rzqf57zcgs7y33"; };
    type = "github";
    owner = "LnL7";
    repo = "nix-darwin";
    rev = "3bfa436c1975674ca465ce34586467be301ff509";
    host = "github.com";
  };
  nix-index-database = {
    outPath = builtins.fetchTarball { url = "https://github.com/nix-community/nix-index-database/archive/8f590b832326ab9699444f3a48240595954a4b10.tar.gz"; sha256 = "0662x6n80gmpw8iavkz2277nanlif6crvjn801rfpjpm18r6z67y"; };
    type = "github";
    owner = "nix-community";
    repo = "nix-index-database";
    rev = "8f590b832326ab9699444f3a48240595954a4b10";
    host = "github.com";
  };
  nixos-wsl = {
    outPath = builtins.fetchTarball { url = "https://github.com/nix-community/nixos-wsl/archive/379d20c55f552e91fb9f3f0382e4a97d3f452943.tar.gz"; sha256 = "0wbj21dpbw0mid24vixa7linmrl1x07fqkghipz1l6nxrfhn23mw"; };
    type = "github";
    owner = "nix-community";
    repo = "nixos-wsl";
    rev = "379d20c55f552e91fb9f3f0382e4a97d3f452943";
    host = "github.com";
  };
  nixpkgs = {
    outPath = builtins.fetchTarball { url = "https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.xz"; sha256 = "0qcdivbik71rkgxmkfr67nwjrgydl8dshg1svrrsipq99bw0a19s"; };
    type = "tarball";
    url = "https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.xz";
  };
  vscode-server = {
    outPath = builtins.fetchTarball { url = "https://github.com/nix-community/nixos-vscode-server/archive/92ce71c3ba5a94f854e02d57b14af4997ab54ef0.tar.gz"; sha256 = "0xjal4zcbmdjdaspfkjbpx1680q7390wfzmj7iad04kp3pc9syf8"; };
    type = "github";
    owner = "nix-community";
    repo = "nixos-vscode-server";
    rev = "92ce71c3ba5a94f854e02d57b14af4997ab54ef0";
    host = "github.com";
  };
  systems = {
    outPath = builtins.fetchTarball { url = "https://github.com/nix-systems/default/archive/da67096a3b9bf56a91d16901293e51ba5b49a27e.tar.gz"; sha256 = "1bzg89hgcr2gvza35vqi4n1jbb2gz1yg4b8p7gry4ihsj2mnnbap"; };
    type = "github";
    owner = "nix-systems";
    repo = "default";
    rev = "da67096a3b9bf56a91d16901293e51ba5b49a27e";
    host = "github.com";
  };
  utils = {
    outPath = builtins.fetchTarball { url = "https://github.com/numtide/flake-utils/archive/11707dc2f618dd54ca8739b309ec4fc024de578b.tar.gz"; sha256 = "1cii9id0k1vsa3r53k54bndyl6kxzgm1nsgj7gncgbp3j61qahlp"; };
    type = "github";
    owner = "numtide";
    repo = "flake-utils";
    rev = "11707dc2f618dd54ca8739b309ec4fc024de578b";
    host = "github.com";
  };
  flake-parts = {
    outPath = builtins.fetchTarball { url = "https://github.com/hercules-ci/flake-parts/archive/57928607ea566b5db3ad13af0e57e921e6b12381.tar.gz"; sha256 = "1bdih1syb2b3zmr493y1404aq3xqp2q2xyx5jr8qyjx0anf26xh2"; };
    type = "github";
    owner = "hercules-ci";
    repo = "flake-parts";
    rev = "57928607ea566b5db3ad13af0e57e921e6b12381";
    host = "github.com";
  };
  crane = {
    outPath = builtins.fetchTarball { url = "https://github.com/ipetkov/crane/archive/8525580bc0316c39dbfa18bd09a1331e98c9e463.tar.gz"; sha256 = "1cc0rpwy0f9g1s8hz6p5w1y1p6cf1qcmhdqy6b6x14sjvd8bv1gk"; };
    type = "github";
    owner = "ipetkov";
    repo = "crane";
    rev = "8525580bc0316c39dbfa18bd09a1331e98c9e463";
    host = "github.com";
  };
  nix-wpe-webkit = {
    outPath = builtins.fetchTarball { url = "https://github.com/eval-exec/nix-wpe-webkit/archive/039c6905b9fe233cd731d06d425762546073094f.tar.gz"; sha256 = "191cphx9ag64nwjz14sgx3ycgfyzl8ip8w0y5mjjm3sk9na6pqn7"; };
    type = "github";
    owner = "eval-exec";
    repo = "nix-wpe-webkit";
    rev = "039c6905b9fe233cd731d06d425762546073094f";
    host = "github.com";
  };
  rust-overlay = {
    outPath = builtins.fetchTarball { url = "https://github.com/oxalica/rust-overlay/archive/9b2965450437541d25fde167d8bebfd01c156cef.tar.gz"; sha256 = "1x90kdfj5mhvkzz98j6sl37ndpgj8yc6im12mynilwg5jimdqrhy"; };
    type = "github";
    owner = "oxalica";
    repo = "rust-overlay";
    rev = "9b2965450437541d25fde167d8bebfd01c156cef";
    host = "github.com";
  };
  flake-compat = {
    outPath = builtins.fetchTarball { url = "https://github.com/edolstra/flake-compat/archive/5edf11c44bc78a0d334f6334cdaf7d60d732daab.tar.gz"; sha256 = "0yqfa6rx8md81bcn4szfp0hjq2f3h9i8zjzhqqyfqdkrj5559nmw"; };
    type = "github";
    owner = "edolstra";
    repo = "flake-compat";
    rev = "5edf11c44bc78a0d334f6334cdaf7d60d732daab";
    host = "github.com";
  };
}
