# @generated by https://codeberg.org/goldstein/unflake
let
  deps = {
    unflake_indirect_nixpkgs = builtins.getFlake "flake:nixpkgs";
  } // builtins.mapAttrs (_: v:
    if builtins.typeOf v.outPath == "set" then
      v.outPath
    else if v?revision then
      { outPath = v.outPath; rev = v.revision; }
    else
      { outPath = v.outPath; }
  ) (import ./npins/default.nix);
  universe = rec {
    unflake_indirect_nixpkgs = ((import "${deps.unflake_indirect_nixpkgs.outPath}/flake.nix").outputs {
      self = unflake_indirect_nixpkgs;
    }) // deps.unflake_indirect_nixpkgs // {
      _flake = true;
      outPath = "${deps.unflake_indirect_nixpkgs.outPath}";
      sourceInfo = deps.unflake_indirect_nixpkgs;
    };
    unflake_github_anthrofract_jjdag = ((import "${deps.unflake_github_anthrofract_jjdag.outPath}/flake.nix").outputs {
      self = unflake_github_anthrofract_jjdag;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_anthrofract_jjdag // {
      _flake = true;
      outPath = "${deps.unflake_github_anthrofract_jjdag.outPath}";
      sourceInfo = deps.unflake_github_anthrofract_jjdag;
    };
    unflake_github_edolstra_flake-compat_flake_false = deps.unflake_github_edolstra_flake-compat_flake_false;
    unflake_github_hercules-ci_flake-parts = ((import "${deps.unflake_github_hercules-ci_flake-parts.outPath}/flake.nix").outputs {
      self = unflake_github_hercules-ci_flake-parts;
      nixpkgs-lib = unflake_github_nix-community_nixpkgs-lib;
    }) // deps.unflake_github_hercules-ci_flake-parts // {
      _flake = true;
      outPath = "${deps.unflake_github_hercules-ci_flake-parts.outPath}";
      sourceInfo = deps.unflake_github_hercules-ci_flake-parts;
    };
    unflake_github_idursun_jjui = ((import "${deps.unflake_github_idursun_jjui.outPath}/flake.nix").outputs {
      self = unflake_github_idursun_jjui;
      flake-parts = unflake_github_hercules-ci_flake-parts;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_idursun_jjui // {
      _flake = true;
      outPath = "${deps.unflake_github_idursun_jjui.outPath}";
      sourceInfo = deps.unflake_github_idursun_jjui;
    };
    unflake_github_jacopone_antigravity-nix = ((import "${deps.unflake_github_jacopone_antigravity-nix.outPath}/flake.nix").outputs {
      self = unflake_github_jacopone_antigravity-nix;
      flake-utils = unflake_github_numtide_flake-utils;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_jacopone_antigravity-nix // {
      _flake = true;
      outPath = "${deps.unflake_github_jacopone_antigravity-nix.outPath}";
      sourceInfo = deps.unflake_github_jacopone_antigravity-nix;
    };
    unflake_github_lnl7_nix-darwin = ((import "${deps.unflake_github_lnl7_nix-darwin.outPath}/flake.nix").outputs {
      self = unflake_github_lnl7_nix-darwin;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    }) // deps.unflake_github_lnl7_nix-darwin // {
      _flake = true;
      outPath = "${deps.unflake_github_lnl7_nix-darwin.outPath}";
      sourceInfo = deps.unflake_github_lnl7_nix-darwin;
    };
    unflake_github_nix-community_nix-index-database = ((import "${deps.unflake_github_nix-community_nix-index-database.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_nix-index-database;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_nix-community_nix-index-database // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_nix-index-database.outPath}";
      sourceInfo = deps.unflake_github_nix-community_nix-index-database;
    };
    unflake_github_nix-community_nixos-vscode-server = ((import "${deps.unflake_github_nix-community_nixos-vscode-server.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_nixos-vscode-server;
      flake-utils = unflake_github_numtide_flake-utils;
      nixpkgs = unflake_indirect_nixpkgs;
    }) // deps.unflake_github_nix-community_nixos-vscode-server // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_nixos-vscode-server.outPath}";
      sourceInfo = deps.unflake_github_nix-community_nixos-vscode-server;
    };
    unflake_github_nix-community_nixos-wsl = ((import "${deps.unflake_github_nix-community_nixos-wsl.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_nixos-wsl;
      flake-compat = unflake_github_edolstra_flake-compat_flake_false;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_nix-community_nixos-wsl // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_nixos-wsl.outPath}";
      sourceInfo = deps.unflake_github_nix-community_nixos-wsl;
    };
    unflake_github_nix-community_nixpkgs-lib = ((import "${deps.unflake_github_nix-community_nixpkgs-lib.outPath}/flake.nix").outputs {
      self = unflake_github_nix-community_nixpkgs-lib;
    }) // deps.unflake_github_nix-community_nixpkgs-lib // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-community_nixpkgs-lib.outPath}";
      sourceInfo = deps.unflake_github_nix-community_nixpkgs-lib;
    };
    unflake_github_nix-systems_default = ((import "${deps.unflake_github_nix-systems_default.outPath}/flake.nix").outputs {
      self = unflake_github_nix-systems_default;
    }) // deps.unflake_github_nix-systems_default // {
      _flake = true;
      outPath = "${deps.unflake_github_nix-systems_default.outPath}";
      sourceInfo = deps.unflake_github_nix-systems_default;
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = ((import "${deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable.outPath}/flake.nix").outputs {
      self = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    }) // deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable // {
      _flake = true;
      outPath = "${deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable.outPath}";
      sourceInfo = deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = ((import "${deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable.outPath}/flake.nix").outputs {
      self = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    }) // deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable // {
      _flake = true;
      outPath = "${deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable.outPath}";
      sourceInfo = deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    };
    unflake_github_numtide_flake-utils = ((import "${deps.unflake_github_numtide_flake-utils.outPath}/flake.nix").outputs {
      self = unflake_github_numtide_flake-utils;
      systems = unflake_github_nix-systems_default;
    }) // deps.unflake_github_numtide_flake-utils // {
      _flake = true;
      outPath = "${deps.unflake_github_numtide_flake-utils.outPath}";
      sourceInfo = deps.unflake_github_numtide_flake-utils;
    };
    unflake_github_schembriaiden_helium-browser-nix-flake = ((import "${deps.unflake_github_schembriaiden_helium-browser-nix-flake.outPath}/flake.nix").outputs {
      self = unflake_github_schembriaiden_helium-browser-nix-flake;
      nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
      utils = unflake_github_numtide_flake-utils;
    }) // deps.unflake_github_schembriaiden_helium-browser-nix-flake // {
      _flake = true;
      outPath = "${deps.unflake_github_schembriaiden_helium-browser-nix-flake.outPath}";
      sourceInfo = deps.unflake_github_schembriaiden_helium-browser-nix-flake;
    };
    unflake_github_sunaku_enthium_ref_v10_flake_false = deps.unflake_github_sunaku_enthium_ref_v10_flake_false;
    unflake_github_vic_den = ((import "${deps.unflake_github_vic_den.outPath}/flake.nix").outputs {
      self = unflake_github_vic_den;
    }) // deps.unflake_github_vic_den // {
      _flake = true;
      outPath = "${deps.unflake_github_vic_den.outPath}";
      sourceInfo = deps.unflake_github_vic_den;
    };
    unflake_github_vic_flake-aspects = ((import "${deps.unflake_github_vic_flake-aspects.outPath}/flake.nix").outputs {
      self = unflake_github_vic_flake-aspects;
    }) // deps.unflake_github_vic_flake-aspects // {
      _flake = true;
      outPath = "${deps.unflake_github_vic_flake-aspects.outPath}";
      sourceInfo = deps.unflake_github_vic_flake-aspects;
    };
    unflake_github_vic_flake-file = ((import "${deps.unflake_github_vic_flake-file.outPath}/flake.nix").outputs {
      self = unflake_github_vic_flake-file;
    }) // deps.unflake_github_vic_flake-file // {
      _flake = true;
      outPath = "${deps.unflake_github_vic_flake-file.outPath}";
      sourceInfo = deps.unflake_github_vic_flake-file;
    };
    unflake_github_vic_import-tree = ((import "${deps.unflake_github_vic_import-tree.outPath}/flake.nix").outputs {
      self = unflake_github_vic_import-tree;
    }) // deps.unflake_github_vic_import-tree // {
      _flake = true;
      outPath = "${deps.unflake_github_vic_import-tree.outPath}";
      sourceInfo = deps.unflake_github_vic_import-tree;
    };
    unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz = ((import "${deps.unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz.outPath}/flake.nix").outputs {
      self = unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz;
    }) // deps.unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz // {
      _flake = true;
      outPath = "${deps.unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz.outPath}";
      sourceInfo = deps.unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz;
    };
  };
  inputs = {
    antigravity = universe.unflake_github_jacopone_antigravity-nix;
    den = universe.unflake_github_vic_den;
    enthium = universe.unflake_github_sunaku_enthium_ref_v10_flake_false;
    flake-aspects = universe.unflake_github_vic_flake-aspects;
    flake-file = universe.unflake_github_vic_flake-file;
    helium = universe.unflake_github_schembriaiden_helium-browser-nix-flake;
    import-tree = universe.unflake_github_vic_import-tree;
    jjdag = universe.unflake_github_anthrofract_jjdag;
    jjui = universe.unflake_github_idursun_jjui;
    nix-darwin = universe.unflake_github_lnl7_nix-darwin;
    nix-index-database = universe.unflake_github_nix-community_nix-index-database;
    nixos-wsl = universe.unflake_github_nix-community_nixos-wsl;
    nixpkgs = universe.unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz;
    vscode-server = universe.unflake_github_nix-community_nixos-vscode-server;
    self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
    withInputs = outputs: let self = outputs (inputs // { inherit self; }); in self;
    __functor = self: self.withInputs;
  };
in inputs