# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  ...
}:

{

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/49a514f4-ba6e-47aa-b3c0-83a650c2e22d";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/45F4-4CED";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/f774218c-ec59-427d-bada-8eb7b6b928b8"; }
  ];

}
