name: nix-fmt

on:
  pull_request:
  push:
    branches: [main]

jobs:
  nix-fmt:
    name: nix-fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v16
        with:
          name: vix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix fmt -- --ci
