name: "Test on Comment"

on:
  issue_comment:
    types: [created]

jobs:
  flake-check:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/test')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v16
        with:
          name: vix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix flake check
